name: NFL Fantasy Dashboard
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          make install
      - name: Format code
        run: |
          python3 -m black *.py src/*.py
      - name: Lint with pylint
        run: |
          python3 -m pylint --disable=R,C *.py src/*.py
      - name: Test with pytest
        run: |
          python3 -m pytest -vv --cov=src --cov=main
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
      - name: Build Container
        run: |
          docker build -t nfl-fantasy-dashboard .
